const types = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    SET_ALERT: 'SET_ALERT',
    REMOVE_ALERT: 'REMOVE_ALERT',
    USER_LOADED: 'USER_LOADED',
    AUTH_ERROR: 'AUTH_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    LOAD_COMPANIES: 'LOAD_COMPANIES',
    LOAD_ERROR: 'LOAD_ERROR',
    GET_COMPANY: 'GET_COMPANY',
    LEAVE_COMPANY: 'LEAVE_COMPANY',
    EDIT_COMPANY: 'EDIT_COMPANY',
    EDITING: 'EDITING',
}

export default types;